---
title: "GANNT chart"
author: "Danielle N"
date: '2022-05-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages}
library(plan)
library(DiagrammeR)
```

```{r cars}
g <- new("gantt")
g <- ganttAddTask(g, "Study 1: Bidirectional MR")
g <- ganttAddTask(g, "Data Curation", "2000-01-01", "2000-03-01", done = 100)
g <- ganttAddTask(g, "Genetic Instrument Selection", "2000-03-01", "2000-09-01", done = 100)
g <- ganttAddTask(g, "Dataset Harmonization", "2000-09-01", "2000-11-01", done = 100)
g <- ganttAddTask(g, "Bidirectional MR Analysis", "2000-11-01", "2001-01-01", done = 100)
g <- ganttAddTask(g, "Sensitivity Analysis", "2001-01-01", "2001-03-01", done = 100)
g <- ganttAddTask(g, "Writeup", "2001-03-01", "2001-05-01", done = 100)
g <- ganttAddTask(g, "Study 2: Drug Target MR")
g <- ganttAddTask(g, "Drug Target Identification", "2001-05-01", "2001-06-01", done = 0)
g <- ganttAddTask(g, "Genetic Instrument Selection", "2001-06-01", "2001-09-01", done = 0)
g <- ganttAddTask(g, "Cis-MR Analysis", "2001-09-01", "2002-01-01", done = 0)
g <- ganttAddTask(g, "Sensitivity analysis", "2002-01-01", "2002-04-01", done = 0)
g <- ganttAddTask(g, "Colocalization analysis", "2002-04-01", "2002-10-01", done = 0)
g <- ganttAddTask(g, "Writeup", "2002-10-01", "2003-01-01", done = 0)


plan::plot(g,
  ylabel = list(font = ifelse(is.na(g[["start"]]), 2, 1)),
  event.time = c("2001-01-01", "2002-01-01"),
  xlim = c("2000-01-01", "2003-01-01"),
  col.done = c("blue"),
  col.notdone = c("red"),
  axes  = TRUE, 
  #las=2,
  maiAdd=c(0.5,0,0,0),
  #cex.axis = 0.9 ,
  time.format = paste((seq(0, 36, by = 3)), sep = "") 
)

line <- 1.5 # adjust this
mtext("Months", side=1, line=line, at = 0.64)







```



